server:
  port: 8079

spring:
  application:
    name: board-server-batch

  datasource:
    url: jdbc:h2:tcp://localhost/../data_user/board
    username: sa
    password: 1234

  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schmea.sql
      data-locations: classpath:sql/data-${spring.sql.init.platform}.sql

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #default_batch_fetch_size: 100

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
