server:
  port: 8081

spring:
  application:
    name: server-rest

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/../data_user/board
    username: sa
    password: 1234

  data:
    rest:
      base-path: /api-rest
      default-page-size: 10
      max-page-size: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true,
#        jdbc.batch_size: 200 # 배치사이즈 설정
#        jdbc.batch_versioned_data: true # 에러가 났을때 잘못된 행수 반환 여부
#        order_inserts: true # insert 구문을 묶어서 일괄처리 함
#        order_updates: true # update 구문을 묶어서 일괄처리함
#        default_batch_fetch_size: 100

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
