server:
  port: 8081

spring:
  application:
    name: server-rest

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #default_batch_fetch_size: 100

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
