server:
  port: 8080

spring:
  application:
    name: board-server-web

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/../data_user/board
    username: sa
    password: 1234

  devtools:
    restart.enabled: false
    livereload.enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(i1DILU4hKyzu6tKYchaRXo1oxrs7LY5j+hCsQDyP2vhQ1Hk7isEGWaZ9N2/HWgTknE0FiJokrz2jILTEtar8SRsCCZQ0u2BZFbst/k8yt2sUl5dzHFPmRw==)
            client-secret: ENC(ztsHqRlsxX68esRFf9NKJx3AKpTDazdkUPqsQf3g/xEm7BJD8Kzc7Q==)

logging:
  level:
    #org.springframework.security: debug
    io.devfactory: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

custom:
  oauth2:
    kakao:
      client-id: ENC(ixrvi1Msas4zcsyuwb94n2KMhPzdbexhJqwf/8CkhsWQbs8jZyco2gHjA6xOJL64)
